version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - app:/upload
    depends_on:
      - db
    environment:
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=1
      - PGSSLMODE=disable
      - JWT_SECRET=${JWT_SECRET}
    command: /app/backend
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
    ports:
      - "5432:5432"
    volumes:
      - ./base.sql:/docker-entrypoint-initdb.d/base.sql:ro

volumes:
  app: