services:
  backend:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - app:/upload
    depends_on:
      - db
    environment:
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT}
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGSSLMODE=disable
      - JWT_SECRET=${JWT_SECRET}

    command: /app/backend
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
    ports:
      - "5432:5432"
    volumes:
      - ./base.sql:/docker-entrypoint-initdb.d/base.sql:ro

volumes:
  app: