name: Build Image
run-name: Build and Publish Docker Image
on: [push]
permissions:
  packages: write
jobs:
  Build-And-Publish:
    runs-on: ubuntu-latest
    environment: JWT_SECRET, datbase
    steps:
      - uses: actions/checkout@v2
      - name: Create .env file
        run: |
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "PGHOST=${{ secrets.PGHOST }}" >> .env
          echo "PGDATABASE=${{ secrets.PGDATABASE }}" >> .env
          echo "PGUSER=${{ secrets.PGUSER }}" >> .env
          echo "PGPASSWORD=${{ secrets.PGPASSWORD }}" >> .env
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/backend:latest .
      
      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository }}/backend:latest  
      - name: Run containers
        run: |
          docker-compose up -d