name: Build Image
run-name: Build and Publish Docker Image
on: [push]
permissions:
  packages: write
jobs:
  Build-And-Publish:
    runs-on: ubuntu-latest
    environment: JWT_SECRET, datbase
    steps:
      - uses: actions/checkout@v2
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Create .env file
        run: |
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "PGHOST=${{ secrets.PGHOST }}" >> .env
          echo "PGDATABASE=${{ secrets.PGDATABASE }}" >> .env
          echo "PGUSER=${{ secrets.PGUSER }}" >> .env
          echo "PGPASSWORD=${{ secrets.PGPASSWORD }}" >> .env
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run containers
        run: |
          docker-compose up -d